version: '3'

services:
  stringer-setup:
    image: stringerrss/stringer:latest
    container_name: stringer-setup
    restart: no
    env_file: .env
    volumes:
      - ./.env:/app/.env
    entrypoint: ["ruby"]
    command: ["/app/docker/init_or_update_env.rb"]

  stringer-postgres:
    image: postgres:16-alpine
    container_name: stringer-postgres
    restart: always
    depends_on:
      stringer-setup:
        condition: service_completed_successfully
    networks:
      - stringer-network
    ports:
      - "54321:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file: .env

  stringer:
    image: stringerrss/stringer:latest
    container_name: stringer
    build: .
    depends_on:
      stringer-postgres:
        condition: service_started
      stringer-setup:
        condition: service_completed_successfully
    restart: always
    ports:
      - "9080:8080"
    networks:
      - stringer-network
    env_file: .env

networks:
  stringer-network:
    external: false

volumes:
  db:
